services:
  imap-spam-cleaner:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: local
    image: imap-spam-cleaner:local
    container_name: imap-spam-cleaner
    hostname: imap-spam-cleaner
    restart: unless-stopped
    volumes:
      - ./.config.yml:/app/config.yml:ro

# SpamAssassin is an optional service
#  spamassassin:
#    image: axllent/spamassassin
#    ports:
#      - "783:783"
#    restart: always
#    environment:
#      - DNS_CHECKS=1
#    volumes:
#      - spamassassin_data:/var/lib/spamassassin
#
#volumes:
#  spamassassin_data: {}
